# Default values for fe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: front-end
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  type: ClusterIP
  port: 5000

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
