apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    specification-identifier: fe-service
spec:
  selector:
    app: fe-service
  ports:
  - port: 5000
    name: http
  type: NodePort
